id: I40A59290
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:48:13+00:00'
last_modified: '2022-06-08T07:36:52.766350+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29518
  title: གངས་ལྗོངས་མདོ་སྨད་གནས་མཆོག་གསུམ་གྱི་གནས་ཡིག་ཕྱོགས་བསྒྲིགས་རྫོགས་ལྡན་འཕྲུལ་གྱི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    D03A:
      image_group_id: I00EGS1017207
      title: ''
      total_pages: 132
      order: 1
      base_file: D03A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
